#!/usr/bin/env bash                                                 
# Initialize the hours and minutes variables                        
hour=0                                         
while [ $hour -lt 13 ]
do
	echo "Hour: $hour"
        minute=1
        while [ $minute -lt 60 ]
        do
		echo "$minute"
	        (( minute++ ))
	done
	((hour++ ))
done
