#!/usr/bin/env bash
# process and pid file

file="/var/run/myscript.pid"

echo $$ > "$file"
trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM SIGQUIT

trap 'echo Y U no love me?!' SIGINT

while :; do
	echo "To infinity and beyond"
	sleep 2
done
