#!/usr/bin/env bash
# init script to manage the process in manage_my_process script
#pid_file="/var/run/my_process.pid"
case "$1" in
	start)
		./manage_my_process &
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		pkill -f ./manage_my_process
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		pkill -f ./manage_my_process
		./manage_my_process &
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
	# make sure to handle no parameter
	echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
esac
